### ISSUE TITLE
Make this a supplemental stylesheet

### ISSUE THREAD

**Issue by erkinalp** [StylishThemes/GitHub-Community-Dark#8]
**Describe the change you'd like**
GitHub and GitHub community share many design and programming elements. Making this a supplemental stylesheet will make it easier to maintain.

**Comment by the-j0k3r** [comment]
> GitHub and GitHub community share many design and programming elements. Making this a supplemental stylesheet will make it easier to maintain.

>Making this a supplemental stylesheet will make it easier to maintain.

Is it less work to maintain as is? Currently this hardly changes the same like GitHub does.

This style is separate on purpose AFAIK, GitHub Dark is massive at 23700K+lines so we need to decouple even more sites form it. 

That said there's a theme generator on the way based on GitHub Dark that this style could do with as in the ways of re-writing this style and Github Dark eeds to be in a msotly automated format, so then it will be irrelevant as mostly will be auto generated.

Also there are plans somewhat underway to decouple the syntax themes from main styles, so that alone will be a massive step forward in terms of reducing duplication by orders of the hunderds of thousands while making adding new styles simple for the end user.

Speaking for myself and out-loud, Its best to wait until there's a theme generator that we can plug this site into, so in this scheme of things this offers no bang for the buck at this time with that in view in future here.

**Comment by xt0rted** [comment]
The community site ([Khoros Communities](https://khoros.com/platform/communities), formerly Lithium Communities), blog ([Wordpress](https://wordpress.com/)), and status site ([Statuspage](https://www.statuspage.io/)) are all 3rd party services so none of the github.com styles apply to them and they end up inflating GitHub Dark even more than it needs to be.

Personally I don't think any of these should be part of the main theme. I use them so infrequently that I don't care they're not styled (I even turn GHD off for all of these sub sites except for the help & developer sites).

**Comment by the-j0k3r** [comment]
made irrelevant by https://github.com/StylishThemes/GitHub-Community-Dark/issues/9

GitHub now uses Discourse.
